### ISSUE TITLE
download_tsx.py

### ISSUE THREAD

**Issue by Neroaway** [gbaier/geonrw#1]
In your code, I donot find the download_tsx.py. Did you forget to upload this file？ Can you upload it

**Comment by gbaier** [comment]
Sorry, my bad. That's a typo. There is no download script for the TerraSAR-x acquisitions. You have to download the ones listed in https://github.com/gbaier/geonrw/blob/main/tsx_aquisitions.txt yourself.

**Comment by Neroaway** [comment]
I think this data is very good, but it's too unfortunate that there is no corresponding SAR data. How do I get these data? In addition, are these SAR data available free of charge?
Thanks!

**Comment by gbaier** [comment]
You can get TerraSAR-X data for research by writing a proposal. Check https://www.sss.terrasar-x.dlr.de/ for details. The process is rather quick and you get the data for free.
